# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170811_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='Write your post here'),
        ),
    ]
